#!/usr/bin/env bash
# Displays information about given/all subdomains.

display() {
	dest=$(dig "$2"."$1"| grep 'ANSWER SECTION' -A1 | awk 'FNR == 2 {print $5}')
	record=$(dig "$2"."$1" | grep 'ANSWER SECTION' -A1 | awk 'FNR == 2 {print $4}')
	echo "The subdomain $2 is a $record record and points to $dest"
}

if [ "$#" -gt 1 ];
then
        display "$1" "$2"
else
	arr=("www" "lb-01" "web-01" "web-02")
	for sub in "${arr[@]}"
        do
                display "$1" "$sub"
        done
fi
