#!/usr/bin/env bash
#Configures an Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update -y
sudo apt-get install nginx -y 
echo "Hello World!" > /var/www/html/index.html

replacement="server_name _;\n\trewrite /redirect_me https://www.pinterest.com/pin/238972323970538189/ permanent;"
sudo sed -i "s|server_name _;|$replacement|" /etc/nginx/sites-available/default

sudo service nginx restart
