#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me is redirecting to another page.

apt-get update -y
apt-get install nginx -y
ufw enable
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html

new_string="server_name _;\n\trewrite ^/redirect_me https://pinterest.com permanent;"

sed -i "s|server_name _;|$new_string|" /etc/nginx/sites-available/default
service nginx restart
