#!/usr/bin/env bash
# Installs and configure HAproxy.
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get update -y
sudo apt-get install haproxy=2.8.\* -y
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null
cp /etc/haproxy/haproxy.cfg ~
#!/usr/bin/env bash
echo -e "\nfrontend http\n\tbind *:80\n\tdefault_backend web\n" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
echo -e "backend web\n\tbalance roundrobin\n\tserver web1 34.229.69.44:80 check\n\tserver web2 100.26.9.101:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy reload
