#!/usr/bin/env bash
# Installs and configures HAproxy loadbalancer.
# sudo apt-get install --no-install-recommends software-properties-common -y
# sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get update -y
sudo apt-get install haproxy -y
# sudo apt-get install haproxy=2.8.\* -y
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null
# A backup
cp /etc/haproxy/haproxy.cfg ~
server_config=\
"
frontend http
    bind *:80
    default_backend web

backend web
    balance roundrobin
    server 37229-web-01 34.229.69.44:80 check
    server 37229-web-02 100.26.9.101:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy restart
