#!/usr/bin/env bash
# Fixing the container so that Nginx is running as the nginx user.

apt-get update -y
apt-get install nginx -y
apt-get install acl -y
useradd nginx > /dev/null
cat /usr/lib/systemd/system/nginx.service > nginx.service.backup
sed -i 's|forking|forking\nRuntimeDirectory=nginx\nUser=nginx\nGroup=nginx\n|' /usr/lib/systemd/system/nginx.service
sed -i 's|www-data|nginx|' /etc/nginx/nginx.conf
sed -i 's|80|8080|' /etc/nginx/sites-available/default
setfacl -R -m u:nginx:rwx /var/log/nginx
setfacl -m u:nginx:rwx /run
chown -R nginx:nginx /usr/share/nginx/
systemctl daemon-reload
service nginx restart
